version: '3'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/local-config.yaml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/local-config.yaml
      - /var/log:/var/log
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
